### PR TITLE
fix dense array using the wrong len method and #188

### LINKED ISSUE #188: tests don't pass locally
An important note is that i have llvm compiled with assertions on.

```
melior-2d0b8d39558e8344: /.../llvm-project-16.0.0.src/mlir/lib/IR/BuiltinAttributes.cpp:924: static mlir::DenseElementsAttr mlir::DenseElementsAttr::get(mlir::ShapedType, ArrayRef<mlir::Attribute>): Assertion `intAttr.getType() == eltType && "expected integer attribute type to equal element type"' failed.
test dialect::scf::tests::compile_index_switch ... ok
error: test failed, to rerun pass `-p melior --lib`

Caused by:
  process didn't exit successfully: `/.../melior/target/debug/deps/melior-2d0b8d39558e8344` (signal: 6, SIGABRT: process abort signal)
```

Since it SIGABRT it's hard to pointpoint what test causes it

### PR DESCRIPTION
**Pull request by edg-l**
fixes #188 

i also fixed some tests using unregistered dialects (catched with llvm assertions on)

### CODE REVIEW

File: melior/src/ir/attribute.rs [hunk 1]
```diff
@@ -136,23 +136,33 @@ from_raw_subtypes!(
...
     fn parse() {
+        let context = create_test_context();
         for attribute in ["unit", "i32", r#""foo""#] {
-            assert!(Attribute::parse(&Context::new(), attribute).is_some());
+            assert!(Attribute::parse(&context, attribute).is_some());
         }
     }
 
     #[test]
+    #[ignore = "Big warning message on llvm with assertions on"]
```
Comment (raviqqe) [inline melior/src/ir/attribute.rs:153]: Note for me. 😄

File: melior/src/ir/value.rs [hunk 2]
```diff
@@ -184,7 +183,7 @@ mod tests {
 
     #[test]
     fn display() {
```
Comment (raviqqe) [inline melior/src/ir/value.rs:185]: Note for me. 😄

**Comment by raviqqe** [comment]
Thank you for refactoring and fixes!

File: melior/src/ir/attribute.rs (hunk 1 above)
Comment (raviqqe) [reply melior/src/ir/attribute.rs:153]: @edg-l Can we actually keep this test? Some warning messsages show up even with LLVM built without assertions. If this test is fundamentally wrong, we should probably change the return type from `Option<Self>` to `Self`.
